import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { BookMarked, ChartNoAxesCombined, Check, ChevronRight, Clock3, CloudOff, Download, FileQuestion, Filter, Heart, Lightbulb, ListChecks, Mail, RotateCcw, Search, Target, Trophy, X } from 'lucide-react';
import { Link, Route, Switch, useParams, Router as WouterRouter } from 'wouter';
import { ErrorBoundary } from '@/components/error-boundary';
import { Toaster } from '@/components/ui/toaster';
import { TooltipProvider } from '@/components/ui/tooltip';
import { AppShell } from '@/components/app-shell';
import { mocks, resources, subjects, superMock, type Mock, type Resource } from '@/data';

const queryClient = new QueryClient();
type Result = { id: string; mockId: string; title: string; subject: string; score: number; total: number; percentage: number; completedAt: string; answers: number[] };

function readStore<T>(key: string, fallback: T): T {
  try { const value = localStorage.getItem(key); return value ? JSON.parse(value) as T : fallback; } catch { return fallback; }
}
function writeStore<T>(key: string, value: T) { localStorage.setItem(key, JSON.stringify(value)); }
function useStore<T>(key: string, fallback: T) {
  const [value, setValue] = useState<T>(() => readStore(key, fallback));
  const update = (next: T | ((old: T) => T)) => setValue((old) => { const value = typeof next === 'function' ? (next as (old: T) => T)(old) : next; writeStore(key, value); return value; });
  return [value, update] as const;
}

function PageHead({ eyebrow, title, description, action }: { eyebrow: string; title: string; description?: string; action?: ReactNode }) {
  useEffect(() => { document.title = `${title} · WASSCE Study`; }, [title]);
  return <div className="page-head"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description && <p className="lead">{description}</p>}</div>{action}</div>;
}
function StatCard({ label, value, note }: { label: string; value: string; note: string }) { return <div className="stat-card" data-testid={`stat-${label.toLowerCase().replaceAll(' ', '-')}`}><div className="stat-label">{label}</div><div className="stat-value">{value}</div><div className="stat-note">{note}</div></div>; }
function ResourceCard({ resource, saved, onSave, onOpen }: { resource: Resource; saved: boolean; onSave: () => void; onOpen?: () => void }) {
  return <article className="resource-card" data-testid={`card-resource-${resource.id}`}><div className="resource-card-top"><div className="resource-icon"><FileQuestion size={19} /></div><span className="verified" title={resource.verifiedStatus}>{resource.verifiedStatus.includes('Verified') ? 'Verified copy' : 'Source labelled'}</span></div><div><h3>{resource.title}</h3><p>{resource.description}</p></div><div className="resource-tags">{resource.tags.map((tag) => <span className="tag" key={tag}>{tag}</span>)}</div><div className="card-actions"><small>{resource.fileSize} · {resource.resourceType} · {resource.year ?? 'No year'}</small><span style={{ display: 'flex', gap: 6, alignItems: 'center' }}><button className="icon-button" onClick={onSave} aria-label={saved ? 'Remove from saved' : 'Save resource'} data-testid={`button-save-resource-${resource.id}`}><Heart size={15} fill={saved ? 'currentColor' : 'none'} /></button><a className="button button-quiet" href={resource.filePath} download onClick={onOpen} data-testid={`button-download-resource-${resource.id}`}>Save PDF</a><a className="button button-primary" href={resource.filePath} target="_blank" rel="noreferrer" onClick={onOpen} data-testid={`button-open-resource-${resource.id}`}>Open</a></span></div></article>;
}
function FooterDisclaimer() { return <div className="footer-note">WASSCE Study is an independent revision companion. It is not affiliated with, endorsed by, or representative of WAEC. Always confirm official dates, rules and results through WAEC Ghana.</div>; }
function AdPlaceholder() { return <div className="ad-placeholder" aria-label="Reserved advertising space"><span>Ad space</span><small>Reserved for future approved advertising · no ads are active</small></div>; }

function Home() {
  const [results] = useStore<Result[]>('wassce-results', []);
  const [saved, setSaved] = useStore<string[]>('wassce-saved', []);
  const completed = results.length;
  const average = completed ? Math.round(results.reduce((sum, result) => sum + result.percentage, 0) / completed) : 0;
  const last = results[0];
  const subjectProgress = subjects.slice(0, 4).map((subject, index) => ({ subject, value: Math.min(96, [68, 51, 37, 24][index] + (results.filter((result) => result.subject === subject).length * 8)) }));
  return <div className="page"><section className="hero-card"><div className="hero-copy"><div className="eyebrow" style={{ color: 'hsl(43 75% 67%)' }}>Your study desk · ready when you are</div><h1>Small, steady work adds up.</h1><p>Keep your WASSCE preparation practical: one paper, one focused mock, one useful review at a time.</p><Link href="/mocks" className="button button-gold" data-testid="button-hero-mocks">Start a mock <ChevronRight size={15} /></Link><div className="hero-meta"><span><strong>Today</strong> · 25 min focus</span><span>and</span><span>Works with saved content</span></div></div></section>
    <div className="grid-4 stats-row"><StatCard label="Completed mocks" value={String(completed).padStart(2, '0')} note={completed ? 'Keep the rhythm' : 'Your first is waiting'} /><StatCard label="Average score" value={`${average}%`} note={average ? 'Across your attempts' : 'No score yet'} /><StatCard label="Saved resources" value={String(saved.length).padStart(2, '0')} note="Available offline" /><StatCard label="Study streak" value={completed ? `${Math.min(7, completed + 1)} days` : 'Start today'} note="Consistency beats cramming" /></div>
    <div className="grid-2"><section className="panel"><div className="section-head" style={{ marginTop: 0 }}><h2 className="panel-title">Your subject map</h2><Link href="/progress" data-testid="link-home-progress">View progress</Link></div><div className="subject-list">{subjectProgress.map(({ subject, value }, i) => <div className="subject-row" key={subject}><span>{subject}</span><div className="progress-track"><div className={`progress-fill ${i === 1 ? 'gold' : i === 2 ? 'coral' : ''}`} style={{ width: `${value}%` }} /></div><strong>{value}%</strong></div>)}</div></section><section className="panel"><div className="section-head" style={{ marginTop: 0 }}><h2 className="panel-title">Pick up where you left off</h2><Link href="/resources" data-testid="link-home-library">Browse all</Link></div>{last ? <div className="callout"><Trophy size={18} /><span><strong>{last.title}</strong><br />You scored {last.percentage}% on your latest attempt. Review the answers before trying another paper.</span></div> : <div className="empty-state" style={{ padding: '27px 16px' }}><Target size={25} /><strong>No mock completed yet</strong><p>Try a short mock to create your first progress marker.</p><Link href="/mocks" className="button button-primary" data-testid="button-empty-start">Browse mocks</Link></div>}</section></div>
    <div className="section-head"><h2>Useful starting points</h2><Link href="/guides" data-testid="link-home-guides">See study guides</Link></div><div className="grid-3">{resources.slice(0, 3).map((resource) => <ResourceCard key={resource.id} resource={resource} saved={saved.includes(resource.id)} onSave={() => setSaved((old) => old.includes(resource.id) ? old.filter((id) => id !== resource.id) : [...old, resource.id])} />)}</div><AdPlaceholder /><FooterDisclaimer />
  </div>;
}

function ResourcesPage() {
  const [saved, setSaved] = useStore<string[]>('wassce-saved', []);
  const [query, setQuery] = useState('');
  const [subject, setSubject] = useState('All subjects');
  const [year, setYear] = useState('All years');
  const [type, setType] = useState('All types');
  const years = Array.from(new Set(resources.map((resource) => resource.year).filter((value): value is number => value !== null))).sort((a, b) => b - a);
  const filtered = useMemo(() => resources.filter((resource) => (subject === 'All subjects' || resource.subject === subject) && (year === 'All years' || String(resource.year) === year) && (type === 'All types' || resource.resourceType === type) && `${resource.title} ${resource.description} ${resource.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())), [query, subject, year, type]);
  const toggleSaved = (id: string) => setSaved((old) => old.includes(id) ? old.filter((item) => item !== id) : [...old, id]);
  return <div className="page"><PageHead eyebrow="The library" title="Resources that earn their space." description="Past questions, answers and independent mocks. Search once, save what matters, and keep studying without a signal." action={<Link href="/downloads" className="button button-outline" data-testid="button-view-downloads"><Download size={16} /> Saved ({saved.length})</Link>} /><div className="filters"><div style={{ position: 'relative', flex: 1, minWidth: 190 }}><Search size={15} style={{ position: 'absolute', left: 11, top: 12, color: 'hsl(var(--muted-foreground))' }} /><input className="input" style={{ paddingLeft: 34, width: '100%' }} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search papers, topics or subjects" aria-label="Search resources" data-testid="input-search-resources" /></div><select className="select" value={subject} onChange={(event) => setSubject(event.target.value)} aria-label="Filter by subject" data-testid="select-resource-subject"><option>All subjects</option>{subjects.map((item) => <option key={item}>{item}</option>)}</select><select className="select" value={year} onChange={(event) => setYear(event.target.value)} aria-label="Filter by year" data-testid="select-resource-year"><option>All years</option>{years.map((item) => <option key={item}>{item}</option>)}</select><select className="select" value={type} onChange={(event) => setType(event.target.value)} aria-label="Filter by resource type" data-testid="select-resource-type"><option>All types</option>{Array.from(new Set(resources.map((item) => item.resourceType))).map((item) => <option key={item}>{item}</option>)}</select><span style={{ display: 'flex', alignItems: 'center', gap: 5, color: 'hsl(var(--muted-foreground))', fontSize: 11 }}><Filter size={14} /> {filtered.length} results</span></div>{filtered.length ? <div className="grid-3">{filtered.map((resource) => <ResourceCard key={resource.id} resource={resource} saved={saved.includes(resource.id)} onSave={() => toggleSaved(resource.id)} />)}</div> : <div className="empty-state"><Search size={27} /><h3>No matching resources</h3><p>Try a subject name, a year, or clear one of the filters.</p><button className="button button-quiet" onClick={() => { setQuery(''); setSubject('All subjects'); setYear('All years'); setType('All types'); }} data-testid="button-clear-resource-filters">Clear filters</button></div>}<FooterDisclaimer /></div>;
}

function DownloadsPage() {
  const [saved, setSaved] = useStore<string[]>('wassce-saved', []);
  const items = resources.filter((resource) => saved.includes(resource.id));
  return <div className="page"><PageHead eyebrow="Your shelf" title="Saved for the quiet moments." description="These resources are kept on this device for quick access when your data runs out." /><div className="callout" style={{ marginBottom: 20 }}><Download size={18} /><span>V1 saves your study list locally. In a production app, downloads would be verified and stored by the device.</span></div>{items.length ? <div className="grid-2">{items.map((resource) => <ResourceCard key={resource.id} resource={resource} saved onSave={() => setSaved((old) => old.filter((id) => id !== resource.id))} onOpen={() => {}} />)}</div> : <div className="empty-state"><BookMarked size={28} /><h3>Your shelf is empty</h3><p>Save a past paper or guide from the resource library and it will appear here.</p><Link href="/resources" className="button button-primary" data-testid="button-empty-downloads">Find resources</Link></div>}<FooterDisclaimer /></div>;
}

function MocksPage({ superMocks = false }: { superMocks?: boolean }) {
  const available = superMocks ? [superMock] : mocks;
  return <div className="page"><PageHead eyebrow={superMocks ? 'Long-form practice' : 'Practice room'} title={superMocks ? 'Super mocks.' : 'A mock is a conversation with your gaps.'} description={superMocks ? 'Longer simulations for building pacing, focus and exam-day stamina.' : 'Short, focused sets for the days when you can give fifteen minutes. Every answer comes with a reason.'} />{superMocks && <div className="callout" style={{ marginBottom: 20 }}><Clock3 size={18} /><span>Super mocks are intentionally paced. Set aside a clear block of time, silence notifications, and treat the timer as part of the practice.</span></div>}<div className="grid-3">{available.map((mock) => <MockCard key={mock.id} mock={mock} superMock={superMocks} />)}</div><FooterDisclaimer /></div>;
}
function MocksRoute() { return <MocksPage />; }
function SuperMocksPage() { return <MocksPage superMocks />; }
function MockCard({ mock, superMock }: { mock: Mock; superMock?: boolean }) { return <article className="mock-card" data-testid={`card-mock-${mock.id}`}><div className="mock-top"><div><div className="difficulty">{mock.difficulty} · {mock.subject}</div><h3 style={{ marginTop: 7 }}>{mock.title}</h3></div><div className="resource-icon"><Target size={19} /></div></div><p>{superMock ? 'A longer simulation using the same dependable question flow.' : 'A compact check-in designed to reveal what to review next.'}</p><div className="mock-meta"><span><Clock3 size={14} /> {mock.durationMinutes} min</span><span><ListChecks size={14} /> {mock.questionCount} questions</span></div><Link href={`/mocks/${mock.id}`} className="button button-primary" data-testid={`button-start-mock-${mock.id}`}>Begin practice <ChevronRight size={15} /></Link></article>; }

function ExamPage() {
  const { id } = useParams<{ id: string }>();
  const mock = id === superMock.id ? superMock : mocks.find((item) => item.id === id) || mocks[0];
  const [current, setCurrent] = useState(0);
  const [answers, setAnswers] = useState<number[]>([]);
  const [submitted, setSubmitted] = useState(false);
  const [timedOut, setTimedOut] = useState(false);
  const [remainingSeconds, setRemainingSeconds] = useState(mock.durationMinutes * 60);
  const question = mock.questions[current];
  const answer = answers[current];
  const finish = () => {
    const score = mock.questions.reduce((total, item, index) => total + (answers[index] === item.answer ? 1 : 0), 0);
    const result: Result = { id: `${mock.id}-${Date.now()}`, mockId: mock.id, title: mock.title, subject: mock.subject, score, total: mock.questions.length, percentage: Math.round((score / mock.questions.length) * 100), completedAt: new Date().toISOString(), answers };
    const old = readStore<Result[]>('wassce-results', []); writeStore('wassce-results', [result, ...old]); setSubmitted(true);
  };
  useEffect(() => {
    if (submitted) return;
    const timer = window.setInterval(() => {
      setRemainingSeconds((seconds) => {
        if (seconds <= 1) {
          window.clearInterval(timer);
          setTimedOut(true);
          return 0;
        }
        return seconds - 1;
      });
    }, 1000);
    return () => window.clearInterval(timer);
  }, [submitted]);
  useEffect(() => {
    if (timedOut && !submitted) finish();
  }, [timedOut]);
  const formattedTime = `${String(Math.floor(remainingSeconds / 60)).padStart(2, '0')}:${String(remainingSeconds % 60).padStart(2, '0')}`;
  if (submitted) {
    const score = mock.questions.reduce((total, item, index) => total + (answers[index] === item.answer ? 1 : 0), 0);
    return <div className="page"><div className="exam-shell"><div className="question-card" style={{ textAlign: 'center' }}><div className="resource-icon" style={{ margin: '0 auto 18px', width: 54, height: 54 }}><Trophy size={28} /></div><div className="eyebrow">{timedOut ? 'Time reached · practice complete' : 'Practice complete'}</div><h1 style={{ marginTop: 7 }}>{Math.round((score / mock.questions.length) * 100)}%</h1><p className="lead" style={{ marginInline: 'auto' }}>You got {score} of {mock.questions.length} correct on {mock.title}.</p><div className="callout" style={{ textAlign: 'left', margin: '22px 0' }}><Lightbulb size={17} /><span>Read the explanations in your own time. A score is a direction, not a verdict.</span></div><div className="review-list" style={{ textAlign: 'left', display: 'grid', gap: 10, marginBottom: 22 }}>{mock.questions.map((item, index) => <div className={`review-row ${answers[index] === item.answer ? 'review-correct' : 'review-wrong'}`} key={item.id}><strong>{index + 1}. {answers[index] === item.answer ? 'Correct' : 'Review'}</strong><span>{item.explanation}</span></div>)}</div><span style={{ display: 'flex', justifyContent: 'center', gap: 9, flexWrap: 'wrap' }}><Link href="/progress" className="button button-primary" data-testid="button-view-result">View progress</Link><button className="button button-outline" onClick={() => { setAnswers([]); setCurrent(0); setSubmitted(false); setTimedOut(false); setRemainingSeconds(mock.durationMinutes * 60); }} data-testid="button-retry-mock"><RotateCcw size={15} /> Try again</button></span></div></div></div>;
  }
  return <div className="page"><div className="exam-shell"><div className="page-head" style={{ marginBottom: 20 }}><div><div className="eyebrow">{mock.subject} · {mock.durationMinutes} minutes</div><h1>{mock.title}</h1></div><span style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap', justifyContent: 'flex-end' }}><span className={`timer-chip ${remainingSeconds <= 60 ? 'timer-warning' : ''}`} aria-label="Time remaining"><Clock3 size={15} /> {formattedTime}</span><Link href="/mocks" className="button button-outline" data-testid="button-exit-exam">Exit</Link></span></div><div className="question-nav" aria-label="Question navigation" style={{ display: 'flex', gap: 6, flexWrap: 'wrap', marginBottom: 16 }}>{mock.questions.map((item, index) => <button key={item.id} className={`question-nav-button ${current === index ? 'active' : ''} ${answers[index] !== undefined ? 'answered' : ''}`} onClick={() => setCurrent(index)} aria-label={`Go to question ${index + 1}`}>{index + 1}</button>)}</div><div className="progress-track" style={{ marginBottom: 23 }}><div className="progress-fill" style={{ width: `${((current + (answer !== undefined ? 1 : 0)) / mock.questions.length) * 100}%` }} /></div><div className="question-card"><div className="question-number">QUESTION {String(current + 1).padStart(2, '0')} / {String(mock.questions.length).padStart(2, '0')}</div><h2>{question.prompt}</h2><div>{question.options.map((option, index) => <button className={`option ${answer === index ? 'selected' : ''}`} key={option} onClick={() => setAnswers((old) => { const next = [...old]; next[current] = index; return next; })} data-testid={`button-answer-${current}-${index}`}><span className="option-key">{String.fromCharCode(65 + index)}</span><span>{option}</span>{answer === index && <Check size={16} style={{ marginLeft: 'auto' }} />}</button>)}</div></div><div className="exam-footer"><span style={{ color: 'hsl(var(--muted-foreground))', fontSize: 11 }}>{answer === undefined ? 'Choose one answer' : 'Answer selected'}</span><span style={{ display: 'flex', gap: 7 }}>{current > 0 && <button className="button button-outline" onClick={() => setCurrent((value) => value - 1)} data-testid="button-previous-question">Previous</button>}{current < mock.questions.length - 1 ? <button className="button button-primary" onClick={() => setCurrent((value) => value + 1)} disabled={answer === undefined} data-testid="button-next-question">Next question <ChevronRight size={15} /></button> : <button className="button button-gold" onClick={finish} disabled={answer === undefined} data-testid="button-submit-mock">Finish mock <Check size={15} /></button>}</span></div></div></div>;
}

function ProgressPage() {
  const [results] = useStore<Result[]>('wassce-results', []);
  const average = results.length ? Math.round(results.reduce((sum, result) => sum + result.percentage, 0) / results.length) : 0;
  return <div className="page"><PageHead eyebrow="Your record" title="Progress you can act on." description="A simple record of attempts on this device. Use it to decide what deserves your next study session." /><div className="grid-4 stats-row"><StatCard label="Completed mocks" value={String(results.length).padStart(2, '0')} note="All time on this device" /><StatCard label="Average score" value={`${average}%`} note={results.length ? 'Keep reviewing explanations' : 'Complete a mock first'} /><StatCard label="Best score" value={results.length ? `${Math.max(...results.map((r) => r.percentage))}%` : '—'} note="Your personal high" /><StatCard label="Streak" value={results.length ? `${Math.min(7, results.length + 1)} days` : '0 days'} note="One session at a time" /></div><div className="grid-2"><section className="panel"><h2 className="panel-title">Subject progress</h2><div className="subject-list">{subjects.slice(0, 5).map((subject, index) => { const subjectResults = results.filter((result) => result.subject === subject); const score = subjectResults.length ? Math.round(subjectResults.reduce((sum, result) => sum + result.percentage, 0) / subjectResults.length) : [42, 28, 18, 0, 0][index]; return <div className="subject-row" key={subject}><span>{subject}</span><div className="progress-track"><div className="progress-fill" style={{ width: `${score}%` }} /></div><strong>{score}%</strong></div>; })}</div></section><section className="panel"><h2 className="panel-title">Recent results</h2>{results.length ? <div className="table-wrap"><table><thead><tr><th>Mock</th><th>Score</th><th>Date</th></tr></thead><tbody>{results.slice(0, 6).map((result) => <tr key={result.id}><td>{result.title}</td><td className={result.percentage >= 50 ? 'score-good' : ''}>{result.percentage}%</td><td>{new Date(result.completedAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' })}</td></tr>)}</tbody></table></div> : <div className="empty-state" style={{ padding: '25px 15px' }}><ChartNoAxesCombined size={25} /><p>Complete a mock to see your results here.</p><Link className="button button-primary" href="/mocks" data-testid="button-progress-mocks">Take a mock</Link></div>}</section></div><FooterDisclaimer /></div>;
}

function ReportsPage() {
  const reports = [{ year: 2023, subject: 'Core Mathematics', title: 'Examiner insight · working and presentation', focus: 'Use clear working, label diagrams and make every method visible so a marker can follow your reasoning.' }, { year: 2022, subject: 'English Language', title: 'Examiner insight · answering the task', focus: 'Strong responses stay close to the question, organise ideas clearly and use evidence instead of general statements.' }, { year: 2021, subject: 'Integrated Science', title: 'Examiner insight · precision', focus: 'Name processes accurately, include units in calculations and use labelled diagrams where they add meaning.' }, { year: 2021, subject: 'Government', title: 'Examiner insight · explanation', focus: 'Definitions are a starting point. Follow them with relevant explanation, examples and a direct link to the question.' }];
  const [subject, setSubject] = useState('All subjects');
  const [year, setYear] = useState('All years');
  const filtered = reports.filter((report) => (subject === 'All subjects' || report.subject === subject) && (year === 'All years' || String(report.year) === year));
  return <div className="page"><PageHead eyebrow="Learn from the marking desk" title="Examiner reports." description="Original revision summaries based on common response patterns. These are not official WAEC reports; they are practical guidance for your next paper." /><div className="filters"><select className="select" value={subject} onChange={(event) => setSubject(event.target.value)} aria-label="Filter reports by subject"><option>All subjects</option>{Array.from(new Set(reports.map((report) => report.subject))).map((item) => <option key={item}>{item}</option>)}</select><select className="select" value={year} onChange={(event) => setYear(event.target.value)} aria-label="Filter reports by year"><option>All years</option>{Array.from(new Set(reports.map((report) => report.year))).sort((a, b) => b - a).map((item) => <option key={item}>{item}</option>)}</select><span style={{ color: 'hsl(var(--muted-foreground))', fontSize: 11 }}>{filtered.length} summaries</span></div><div className="grid-3">{filtered.map((report) => <article className="info-card mock-card" key={`${report.subject}-${report.year}`}><div className="difficulty">{report.year} · {report.subject}</div><h3>{report.title}</h3><p>{report.focus}</p><div className="callout" style={{ marginTop: 16, fontSize: 12 }}>Original educational summary · official status not claimed</div></article>)}</div><div className="prose-block" style={{ marginTop: 35 }}><h2>How to use a report</h2><p>Read a summary after marking a paper yourself. Circle patterns, not isolated mistakes: unclear working, skipped instructions, weak definitions or answers that do not address the command word.</p></div><FooterDisclaimer /></div>;
}

const guideContent: Record<string, { title: string; eyebrow: string; intro: string; sections: [string, string][] }> = {
  '/guides': { eyebrow: 'Study guides', title: 'Make revision easier to return to.', intro: 'Good preparation is not a heroic burst. It is a repeatable loop: retrieve, practise, mark, repair.', sections: [['A 25-minute study loop', 'Choose one narrow topic. Spend five minutes recalling what you know without notes, fifteen minutes on questions, then five minutes writing the one thing you will repair next.'], ['Use papers as a map', 'Do not wait until you feel ready. A past paper shows which parts of the syllabus deserve your attention. Mark it honestly and turn missed questions into a short list.'], ['Keep a mistake book', 'Write the question type, your first wrong idea, and the corrected method. Review this list before starting a new paper.']], },
  '/exam-guides': { eyebrow: 'Exam preparation', title: 'Prepare for the room, not just the paper.', intro: 'A calm exam day begins with small decisions made earlier: timing, materials, sleep and knowing what the instructions ask.', sections: [['The week before', 'Complete one timed paper, check your materials, and revisit recurring mistakes. Avoid starting five new topics at once.'], ['When time begins', 'Read the paper instructions before answering. Scan the sections and make a quiet time plan. Leave a few minutes to check question numbers and units.'], ['When a question stalls you', 'Mark it, take one breath, and move on. Return when the rest of the paper has given your brain another route into the problem.']], },
  '/dos-donts': { eyebrow: 'Exam room notes', title: 'Do the simple things well.', intro: 'Practical reminders for a fair attempt. Save this page and read it the night before a paper.', sections: [['Do', 'Read every instruction. Number answers clearly. Show working in Mathematics and Science. Use the command word in the question to shape your answer. Check units, labels and page numbers.'], ['Do not', 'Do not spend the whole paper on one stubborn question. Do not write in the margins if your answer needs room. Do not assume a neat guess is better than a clearly shown method.'], ['A final check', 'Use the final minutes for omissions and transcription errors first. Then check calculations and whether each part of a multi-part question has an answer.']], },
};
function GuidePage({ path }: { path: string }) { const content = guideContent[path]; return <div className="page"><PageHead eyebrow={content.eyebrow} title={content.title} description={content.intro} /><div className="prose-block">{content.sections.map(([heading, body]) => <section key={heading}><h2>{heading}</h2><p>{body}</p></section>)}</div><div className="callout" style={{ maxWidth: 760, marginTop: 30 }}><Lightbulb size={18} /><span>Keep this practical: the best guide is the one you can use during your next study session.</span></div><FooterDisclaimer /></div>; }

function SimplePage({ title, eyebrow, children }: { title: string; eyebrow: string; children: ReactNode }) { return <div className="page"><PageHead eyebrow={eyebrow} title={title} /> <div className="prose-block">{children}</div><FooterDisclaimer /></div>; }
function AboutPage() { return <SimplePage eyebrow="About this desk" title="A dependable place to prepare."><p>WASSCE Study is a frontend-only study companion for Ghanaian students. It keeps the useful parts close: papers, short mocks, explanations and a record of your own effort.</p><h2>Independent by design</h2><p>This project is not affiliated with WAEC, does not issue official papers or results, and does not replace a teacher or official announcement. We use clear labels so you know what you are reading.</p><h2>Built for real conditions</h2><p>The interface is intentionally light, touch-friendly and usable with saved content. Your saved resources and practice results stay in your browser on this device.</p></SimplePage>; }
function ContactPage() { const [sent, setSent] = useState(false); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSent(true); }; return <SimplePage eyebrow="Reach out" title="Tell us what would help."><p>Found an unclear explanation or have a suggestion for a more useful revision tool? This V1 contact form keeps your note on this device only.</p><p><strong>Email:</strong> <a href="mailto:abdulsammedtakiyudeen@gmail.com">abdulsammedtakiyudeen@gmail.com</a></p>{sent ? <div className="callout"><Check size={18} /><span>Thanks. Your note has been recorded locally for this session.</span></div> : <form onSubmit={submit} style={{ display: 'grid', gap: 12, maxWidth: 560 }}><label style={{ fontSize: 12, fontWeight: 700 }}>Your note<input className="input" required style={{ width: '100%', marginTop: 7 }} placeholder="What should we improve?" data-testid="input-contact-note" /></label><label style={{ fontSize: 12, fontWeight: 700 }}>Optional email<input className="input" type="email" style={{ width: '100%', marginTop: 7 }} placeholder="For a reply" data-testid="input-contact-email" /></label><button className="button button-primary" type="submit" data-testid="button-submit-contact"><Mail size={15} /> Save note</button></form>}</SimplePage>; }
function LegalPage({ kind }: { kind: 'privacy' | 'terms' | 'disclaimer' }) { const content = { privacy: ['Privacy, kept plainly', 'WASSCE Study V1 stores saved resources, theme preference and practice results in your browser’s localStorage. We do not request an account, collect a name, or send your study history to a server. Clear your browser site data to remove it.'], terms: ['Terms for using this desk', 'Use the platform for personal study. Do not present its independent summaries or local results as official WAEC material. Content may contain mistakes; cross-check important information with your school and official sources.'], disclaimer: ['Important disclaimer', 'WASSCE Study is independent and not affiliated with, endorsed by, or representative of the West African Examinations Council (WAEC). Past-paper references, study summaries and practice questions are for revision only. Official examination rules, timetables, results and materials come from WAEC Ghana.'] }[kind]; return <SimplePage eyebrow="Good to know" title={content[0]}><p>{content[1]}</p><h2>In short</h2><p>Use this as a calm study companion, not as a replacement for your teacher, school or official examination communications.</p></SimplePage>; }
function NotFound() { return <div className="page"><div className="empty-state" style={{ maxWidth: 560, margin: '9vh auto' }}><X size={28} /><div className="eyebrow">404 · page not found</div><h1 style={{ marginTop: 7 }}>That page took a wrong turn.</h1><p>Try the study desk or browse the resource library.</p><Link href="/" className="button button-primary" data-testid="button-not-found-home">Back to overview</Link></div></div>; }
function OfflinePage() { return <SimplePage eyebrow="Offline mode" title="Your desk still works."><div className="callout"><CloudOff size={18} /><span>When your connection drops, saved resources and local mock results remain available on this device.</span></div><h2>Before you go offline</h2><p>Save the papers and guides you expect to need. Complete a mock while connected if you want to make sure its questions are already in your browser.</p><Link href="/downloads" className="button button-primary" data-testid="button-offline-downloads">Open saved shelf</Link></SimplePage>; }

function Router() {
  return <AppShell><ErrorBoundary resetKey={location.pathname}><Switch><Route path="/" component={Home} /><Route path="/resources" component={ResourcesPage} /><Route path="/downloads" component={DownloadsPage} /><Route path="/mocks/:id" component={ExamPage} /><Route path="/mocks" component={MocksRoute} /><Route path="/super-mocks" component={SuperMocksPage} /><Route path="/reports" component={ReportsPage} /><Route path="/guides" component={() => <GuidePage path="/guides" />} /><Route path="/exam-guides" component={() => <GuidePage path="/exam-guides" />} /><Route path="/dos-donts" component={() => <GuidePage path="/dos-donts" />} /><Route path="/progress" component={ProgressPage} /><Route path="/about" component={AboutPage} /><Route path="/contact" component={ContactPage} /><Route path="/privacy" component={() => <LegalPage kind="privacy" />} /><Route path="/terms" component={() => <LegalPage kind="terms" />} /><Route path="/disclaimer" component={() => <LegalPage kind="disclaimer" />} /><Route path="/offline" component={OfflinePage} /><Route component={NotFound} /></Switch></ErrorBoundary></AppShell>;
}
function App() { return <QueryClientProvider client={queryClient}><TooltipProvider><WouterRouter base={import.meta.env.BASE_URL.replace(/\/$/, '')}><Router /></WouterRouter><Toaster /></TooltipProvider></QueryClientProvider>; }
export default App;